# noinspection YAMLSchemaValidation
name: dragon-pickup
version: '${version}'
main: pers.ketikai.minecraft.spigot.dragonpickup.DragonPickup
load: STARTUP
authors:
- ketikai
depend:
- minecraft-next
- DragonCore
- NeigeItems
commands:
  dragon-pickup:
    aliases:
    - d-pickup
